// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function isValidDate(value) {
  if (value !== undefined) {
    var dateWrapper = new Date(value);
    return !isNaN(dateWrapper.valueOf());
  } else {
    return false;
  }
}

function DatePickerComponent(Props, props) {
  React.useState((function () {
          return /* () */0;
        }));
  return /* () */0;
}

var make = DatePickerComponent;

exports.isValidDate = isValidDate;
exports.make = make;
/* react Not a pure module */
