// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var DatePickerComponent$ReactHooksTemplate = require("./DatePickerComponent.bs.js");

function handle($$event) {
  console.log("cambio");
  return /* () */0;
}

ReactDOMRe.renderToElementWithId(React.createElement(DatePickerComponent$ReactHooksTemplate.make, {
          props: /* record */[
            /* value */undefined,
            /* hints */false,
            /* dayHint */"",
            /* monthHint */"",
            /* yearHint */"",
            /* className */"",
            /* maxLength */2,
            /* onChange */handle
          ]
        }), "index1");

exports.handle = handle;
/*  Not a pure module */
