// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var DatePickerComponent$ReactHooksTemplate = require("./DatePickerComponent.bs.js");

function handle($$event) {
  if ($$event !== undefined) {
    console.log("cambio: " + Caml_option.valFromOption($$event).toDateString());
    return /* () */0;
  } else {
    console.log("Invalid Date");
    return /* () */0;
  }
}

ReactDOMRe.renderToElementWithId(React.createElement(DatePickerComponent$ReactHooksTemplate.make, {
          props: /* record */[
            /* value */undefined,
            /* hints */false,
            /* dayHint */"",
            /* monthHint */"",
            /* yearHint */"",
            /* className */"",
            /* onChange */handle
          ]
        }), "index1");

exports.handle = handle;
/*  Not a pure module */
