// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var rtdpSpan = Css.style(/* :: */[
      Css.display(Css.inlineBlock),
      /* :: */[
        Css.position(Css.relative),
        /* :: */[
          Css.padding(Css.px(2)),
          /* :: */[
            Css.margin(Css.px(1)),
            /* :: */[
              Css.backgroundColor(Css.hex("ffffff")),
              /* :: */[
                Css.border(Css.px(1), Css.solid, Css.hex("666")),
                /* :: */[
                  Css.borderRadius(Css.px(3)),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var rtdpSpanInner = Css.style(/* :: */[
      Css.border(Css.px(0), Css.none, Css.hex("000")),
      /* :: */[
        Css.padding(Css.px(1)),
        /* :: */[
          Css.margin(Css.px(1)),
          /* :: */[
            Css.whiteSpace(Css.nowrap),
            /* :: */[
              Css.backgroundColor(Css.hex("ffffff")),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var rtdpInput = Css.style(/* :: */[
      Css.border(Css.px(0), Css.none, Css.hex("000")),
      /* :: */[
        Css.padding(Css.px(1)),
        /* :: */[
          Css.margin(Css.px(1)),
          /* :: */[
            Css.whiteSpace(Css.nowrap),
            /* :: */[
              Css.backgroundColor(Css.hex("ffffff")),
              /* :: */[
                Css.width(Css.px(31)),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var plusSizeInput = Css.style(/* :: */[
      Css.width(Css.px(47)),
      /* [] */0
    ]);

var rtdpYearInput = Css.merge(/* :: */[
      rtdpInput,
      /* :: */[
        plusSizeInput,
        /* [] */0
      ]
    ]);

var rtdpSeparator = Css.style(/* :: */[
      Css.color(Css.hex("999999")),
      /* [] */0
    ]);

exports.rtdpSpan = rtdpSpan;
exports.rtdpSpanInner = rtdpSpanInner;
exports.rtdpInput = rtdpInput;
exports.plusSizeInput = plusSizeInput;
exports.rtdpYearInput = rtdpYearInput;
exports.rtdpSeparator = rtdpSeparator;
/* rtdpSpan Not a pure module */
